apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: ghcr.io/msh9991/hello-python:latest
        ports:
        - containerPort: 80