name: Build docker image

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            
            - name: byg docker image
              run: docker build -t "hello-python" ./HelloWorldDocker

              - name: test mit imgage
                run: docker run "hello-python"

